#! python
#coding=utf-8

import os,sys
caffe_root = '/data/darwin-caffe-base/'# caffe的根目录
os.chdir(caffe_root)  #os.chdir()用于改变当前工作目录到指定的路径
sys.path.insert(0,caffe_root+'python')



from caffe.proto import caffe_pb2

def toPrototxt(modelName, deployName):
    with open(modelName, 'rb') as f:
        caffemodel = caffe_pb2.NetParameter()
        caffemodel.ParseFromString(f.read())

    # 兼容新旧版本
    # LayerParameter 消息中的 blobs 保存着可训练的参数
    for item in caffemodel.layers:
        item.ClearField('blobs')
    for item in caffemodel.layer:
        item.ClearField('blobs')
        
    # print(caffemodel)
    with open(deployName, 'w') as f:
        f.write(str(caffemodel))

if __name__ == '__main__':
    modelName = '/data/mgn_caffe/resnet50/orgin_test.caffemodel'
    deployName = '/data/mgn_caffe/resnet50/orgin_test.prototxt'
    toPrototxt(modelName, deployName)
